# Generated by Django 2.0.2 on 2020-12-02 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_auto_20201201_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='summary',
            new_name='Summary',
        ),
    ]
