# Generated by Django 2.0.2 on 2020-12-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0004_auto_20201202_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Title',
            field=models.CharField(default=200, max_length=200),
            preserve_default=False,
        ),
    ]
